# Use the official Golang image to create a build artifact.
# This is the first stage called "builder".
FROM golang:1.23-rc as builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed.
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Build the Go app
RUN go build -o main .

FROM ghcr.io/go-swagger/go-swagger

# Set the Current Working Directory inside the container
WORKDIR /app

ENV GOBIN $GOPATH/bin

COPY --from=builder /app ./

ADD . .

## Commands for swagger docs generation
#  swagger generate spec -o ./swagger.json --scan-models
#  swagger validate swagger.json
#  swagger serve swagger.json -p=6060 --no-open

#RUN  swagger generate spec -o swagger.json --scan-models

ENTRYPOINT  swagger serve swagger.json -p 6060 --no-open

# serving HTTP of 6060
EXPOSE 6060
